# Generated by Django 4.1.2 on 2022-11-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animes", "0002_remove_anime_duration"),
        ("users_animes", "0001_initial"),
        ("users", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="animes",
            field=models.ManyToManyField(
                null=True,
                related_name="users",
                through="users_animes.UserAnimes",
                to="animes.anime",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateTimeField(null=True),
        ),
    ]
