# Generated by Django 4.1.2 on 2022-11-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_animes_alter_user_bio_alter_user_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=120),
        ),
    ]
