<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-11-03 13:49
=======
# Generated by Django 4.1.2 on 2022-11-03 15:40
>>>>>>> 129318116d8dcc6bd3ce956ed2a067e9457713ab

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("episodes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField()),
                ("spoiler", models.BooleanField(default=False)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="episodes.episode",
                    ),
                ),
            ],
        ),
    ]
