# Generated by Django 4.1.2 on 2022-11-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anime",
            name="total_eps",
        ),
    ]
